### ISSUE TITLE
Can't end Raffle

### ISSUE THREAD

**Issue by ppworks123** [y9san9/prizebot#105]
Automatic end does not work, and when attempting manual Raffle, after hitting "Confirm" it shows Loading... and then nothing happens.

**Comment by are27** [comment]
Yeah same here - seems really broken right now

**Comment by y9san9** [comment]
Sad to hear guys. Refently I've tested giveaways with myself and everything was working, can you please provide an example? Write me in telegram t.me/y9san9

**Comment by y9san9** [comment]
We did something wrong with environment, should be nice now. Sorry for troubling 😅
