### ISSUE TITLE
Please allow the bot to 'Forward Messages' in the settings or the bot can't mention you (The setting will be applied within 5 minutes) OK

### ISSUE THREAD

**Issue by AlexHello** [y9san9/prizebot#122]
![Screenshot_20230918_203446_Telegram](https://github.com/y9san9/prizebot/assets/1131580/d8e4c293-ad2d-4f44-8292-dbd558de5b7d)

How do you do this ?

Dmed the bot, checked help, still can't work it out came here :)

Thanks

**Comment by omeringen** [comment]
Same issue. Couldn't find any setting related to this.

**Comment by y9san9** [comment]
<img width="620" alt="Screenshot 2023-10-31 at 15 15 57" src="https://github.com/y9san9/prizebot/assets/46930374/2c3fdb39-29fc-47cd-b663-e889627cfb3f">
