### ISSUE TITLE
Implement exit from giveaway feature

### ISSUE THREAD

**Issue by kylichist** [y9san9/prizebot#36]
Concept: There should be a button "exit" (or emoji) next to the main button.

**Comment by y9san9** [comment]
My position is that the feature may be useful only in giveaways-jokes, but in real giveaways it will only take up a lot of space, isn't it?

**Comment by kylichist** [comment]
I don't think so. User may missclick the button

**Comment by y9san9** [comment]
And randomly have a chance to win something? May be there is a reason to add it in private messages, but not in giveaway message

**Comment by y9san9** [comment]
Anyway, for now I don't see the reason of implementing it, may be later

**Comment by y9neon** [comment]
I think it is worth adding the ability to exit the giveaway, but there is no need to make a separate button. You can make it so that when clicking "participate" a second time, the user leaves the participation. YouTube does the same and a lot of another services do the same.

**Comment by y9san9** [comment]
Wow, awesome idea, why I haven't thought avout it 🙈
